config/routes.rb
Gtests::Application.routes.draw do

  if(AppSettings['redirect_domains']) 
    domains = AppSettings['redirect_domains']
    domains = domains.join('|') if domains.is_a? Array
    constraints(host: /^(#{domains})\./i) do
      match '(*any)' => redirect { |params, request|
        URI.parse(request.url).tap { |uri| uri.host.sub!(/^(#{domains})\./i, '') }.to_s
      }, via: [:get, :post]
    end
  end

  get '/feedback', to: 'feedback#new'
  resources :feedback, only: [:new, :create]

  get 'page/agreement'
  get 'page/faq'

  get "payments/callback"
  get "payments/new"
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get "questions/show"
  get "questions/index"
  get "questions/test"
  mount Rich::Engine => '/rich', :as => 'rich'
  get "comments/recent"
  ActiveAdmin.routes(self)

  require 'scripts/robots_generator'
  get '/robots.txt', to: RobotsGenerator

  get 'comments/recent'

  resources :identities, only: :destroy
  get 'welcome/index'
  devise_for :users,
             controllers: {omniauth_callbacks: 'sessions', registrations: 'registrations'},
             path_names: {:sign_in => 'login', :sign_out => 'logout'}

  resources :categories, only: :index

  resources :categories, path: '', only: [:show] do
    scope module: :training do
      resources :disks, only: [:index, :show] do
        member do
          constraints(question_number: /\d+/) do
            get :test, path: ':question_number'
            post :test_answer, path: ':question_number'
            get :view, path: ':question_number/view'
          end
          get :finish
          get :history
          get :attempt, path: 'attempt/:attempt_id', constraints: { attempt_id: /\d+/ }
        end
      end

      resources :questions, only: [:index, :show] do
        member do
          post :answer
          get :view
        end
      end
    end
  end

  get 'payments/new', as: 'new_payment'
  post 'payments/callback'

  root 'welcome#index'

  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #add_breadcrumb 'Home', '#', :title => 'Back to the Index'

  def index
    #add_breadcrumb 'Index', '/', :title => 'Back to the Index'
    @categories = Category.all
    render locals: { no_ads: true }
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.slim
- cache(@categories)
  .row
    .col-md-6
      = image_tag 'cubes_main_500.png', class: 'img-responsive img-rounded'
    .col-md-6
      h1 Тестирование 1С:Профессионал
      p Сервис онлайн подготовки к тестированию 1С:Профессионал предоставляет удобный способ повысить шансы успешной сдачи
        официальной сертификации по продуктам фирмы 1С. Вы можете проходить все пробные тесты, анализировать ошибки и
        улучшать свои результаты.
      = link_to 'Начать подготовку', categories_path, class: 'btn btn-primary btn-lg'

  hr

  .row
    .col-lg-12
      h2 Направления для подготовки
    .col-lg-12
      /.well.text-center
        /ul.nav.nav-pills.nav-justified
          - @categories.each do |category|
            li = link_to category.name, category_path(category)
      - slice = 3
      - @categories.each_slice(slice) do |group|
        div class="col-md-#{12 / slice}"
          ul.nav.nav-pills.nav-stacked
            - group.each do |category|
              li = link_to category.name, category_path(category)

  hr

  .row
    .col-lg-4
      h2 Что это?
      p Сертификат “1С:Профессионал” является официальным подтверждением того, что его владелец может
        эффективно использовать в своей работе весь спектр возможностей наиболее распространенных программ автоматизации
        бухгалтерского, оперативного торгово-складского, управленческого учета и расчета заработной платы.
        Маленький плюсик в Вашем резюме и первая ступень в системе сертифицирования 1С.
        После него Вы сможете получить сертификат “1С:Специалист”.
      /a class="btn btn-default" href="#" Some info

    .col-lg-4
      h2 Кому это нужно?
      ol
        li Это нужно Вам, если Вы работаете или планируете работать с 1С.
        li Вашему работодателю, чтобы быть уверенным в Вашей компетенции.
        li Вашему самолюбию... Всегда приятно, когда есть чем похвастаться.
      /a class="btn btn-default" href="#" Some info

    .col-lg-4
      h2 Как подготовиться?
      ol
        li На нашем сайте, пройдя #{link_to('регистрацию', new_user_registration_path)}
        li
          ' На сайте 1С с помощью
          a> href="http://edu.1c.ru/dist-training/" target="_blank" учебного тестирования
          | (всего около 15 вопросов по каждому направлению)
      /a class="btn btn-default" href="#" Some info