config/routes.rb
Gtests::Application.routes.draw do

  if(AppSettings['redirect_domains']) 
    domains = AppSettings['redirect_domains']
    domains = domains.join('|') if domains.is_a? Array
    constraints(host: /^(#{domains})\./i) do
      match '(*any)' => redirect { |params, request|
        URI.parse(request.url).tap { |uri| uri.host.sub!(/^(#{domains})\./i, '') }.to_s
      }, via: [:get, :post]
    end
  end

  get '/feedback', to: 'feedback#new'
  resources :feedback, only: [:new, :create]

  get 'page/agreement'
  get 'page/faq'

  get "payments/callback"
  get "payments/new"
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get "questions/show"
  get "questions/index"
  get "questions/test"
  mount Rich::Engine => '/rich', :as => 'rich'
  get "comments/recent"
  ActiveAdmin.routes(self)

  require 'scripts/robots_generator'
  get '/robots.txt', to: RobotsGenerator

  get 'comments/recent'

  resources :identities, only: :destroy
  get 'welcome/index'
  devise_for :users,
             controllers: {omniauth_callbacks: 'sessions', registrations: 'registrations'},
             path_names: {:sign_in => 'login', :sign_out => 'logout'}

  resources :categories, only: :index

  resources :categories, path: '', only: [:show] do
    scope module: :training do
      resources :disks, only: [:index, :show] do
        member do
          constraints(question_number: /\d+/) do
            get :test, path: ':question_number'
            post :test_answer, path: ':question_number'
            get :view, path: ':question_number/view'
          end
          get :finish
          get :history
          get :attempt, path: 'attempt/:attempt_id', constraints: { attempt_id: /\d+/ }
        end
      end

      resources :questions, only: [:index, :show] do
        member do
          post :answer
          get :view
        end
      end
    end
  end

  get 'payments/new', as: 'new_payment'
  post 'payments/callback'

  root 'welcome#index'

  

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user
  before_create :count_points
  after_create :add_points

  private

  def count_points
    self.points = (self.withdraw_amount || 0) / (AppSettings.POINTS_RATE || 1)
  end

  def add_points
    self.user.add_points(self.points, category: Merit::Points::MONEY)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  protect_from_forgery except: :callback
  before_filter :authenticate_user!, except: [:callback]
  before_filter :check_callback_hash, only: :callback

  def callback
    full_params = payment_params rescue return
    puts full_params.inspect
    payment = Payment.find_or_initialize_by(user: User.find_by(id: full_params['user_id']), operation_id: full_params['operation_id'])
    unless payment.update_attributes(full_params)
      logger.error("YandexMoney callback: unable to update attributes for payment. Params: #{full_params.inspect}. Error: #{payment.errors.full_messages}")
    end
  end

  def new
  end

  private

  def check_callback_hash
    params_to_check = params.merge({notification_secret: AppSettings.YANDEX_MONEY_SECRET})
    final_params = []
    %w(notification_type operation_id amount currency datetime sender codepro notification_secret label).each do |field|
      final_params << params_to_check[field]
    end

    head :fobidden unless Digest::SHA1.hexdigest(final_params.join('&')) == params['sha1_hash']

  end

  def payment_params
    label = JSON.parse(params['label'])
    user = User.find_by(id: label['user'].to_i)
    unless user
      logger.error("YandexMoney callback: user with id #{label['user'].to_i} not found. Label: '#{params['label']}'")
      throw Exception.new
    end
    full_params = params.merge({'user_id' => user.id})
    puts full_params.inspect
    full_params.permit(:notification_type, :operation_id, :amount, :withdraw_amount, :datetime, :sender, :codepro, :label, :user_id)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/callback.html.slim
h1 Payments#callback
p Find me in app/views/payments/callback.html.slim

app/views/payments/new.html.slim
- title 'Пополнение баланса баллов'

h1 Пополнение баланса баллов

= form_tag 'https://money.yandex.ru/quickpay/confirm.xml', target: '_blank', method: :post, id: 'points-income', \
            role: 'form', 'data-rate'=> AppSettings.POINTS_RATE, data: {'no-turbolink'=>true} do |f|
  = hidden_field_tag :receiver, AppSettings.YANDEX_MONEY_NUMBER
  = hidden_field_tag :formcomment, '1c-test.ru: Баллы'
  = hidden_field_tag 'short-desc', '1c-test.ru: Баллы'
  = hidden_field_tag 'quickpay-form', 'shop'
  = hidden_field_tag :targets, "Пополнение баллов на 1c-test.ru для пользователя #{current_user.full_name}"
  = hidden_field_tag :label, {user: current_user.id, timestamp: Time.now.utc}.to_json
  .form-group
    = label_tag(:amount, 'Количество баллов')
    .field.input-group#PaymentStep1
      = number_field_tag :amount, AppSettings.DEFAULT_POINTS_INCOME, class: 'form-control', disabled: true
      span.input-group-addon баллов
  .form-group
    = label_tag(:sum, 'Сумма к оплате')
    .field.input-group#PaymentStep2
      = text_field_tag :sum, AppSettings.DEFAULT_POINTS_INCOME * AppSettings.POINTS_RATE, class: 'form-control', readonly: true
      span.input-group-addon рублей

  .form-group
    = label_tag(:paymentType, 'Форма оплаты')
    .field
      .btn-group#PaymentStep3 data-toggle="buttons"
        label.btn.btn-default.active
          input type="radio" name="paymentType" value="PC" checked=true
            span.icons-payment-yamoney
        label.btn.btn-default
          input type="radio" name="paymentType" value="AC"
            span.icons-payment-card

  .form-group
    .field.col-sm-offset-2
      = submit_tag 'Пополнить', class: 'btn btn-primary', id: 'PaymentStep4'

  markdown:
    Пополнение баланса баллов производится через систему Яндекс.Деньги. Вы можете произвести оплату
    со своего счета Яндекс.Денег или с карты международных платежных систем Visa или MasterCard.

    Если у Вас возникли вопросы по оплате, обязательно пишите нам через [форму обратной связи](#{feedback_path}).

  #payments-joyride
    ol#PaymentHints
      li data-target="#PaymentStep1" data-title="Количество баллов" Сначала укажите количество баллов, которое Вы хотите зачислить на счет
      li data-target="#PaymentStep2" data-title="Сумма для оплаты" Затем проверьте сумму, которую необходимо оплатить за пополнение счета
      li data-target="#PaymentStep3" data-title="Форма оплаты" Выбирете удобный способ оплаты: счет сервиса Яндекс.Деньги или банковская карта
      li data-target="#PaymentStep4" data-title="Проверка и оплата" Еще раз проверьте все введенные данные и нажмите кнопку "Оплатить". Вы будете направлены на сайт платежной системы. Вскоре после успешной оплаты Ваш баланс баллов будет пополнен

    a.btn.btn-sm.btn-info#payments-startride href="#joyride" Посмотреть, как платить