config/routes.rb
Gtests::Application.routes.draw do

  if(AppSettings['redirect_domains']) 
    domains = AppSettings['redirect_domains']
    domains = domains.join('|') if domains.is_a? Array
    constraints(host: /^(#{domains})\./i) do
      match '(*any)' => redirect { |params, request|
        URI.parse(request.url).tap { |uri| uri.host.sub!(/^(#{domains})\./i, '') }.to_s
      }, via: [:get, :post]
    end
  end

  get '/feedback', to: 'feedback#new'
  resources :feedback, only: [:new, :create]

  get 'page/agreement'
  get 'page/faq'

  get "payments/callback"
  get "payments/new"
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get "questions/show"
  get "questions/index"
  get "questions/test"
  mount Rich::Engine => '/rich', :as => 'rich'
  get "comments/recent"
  ActiveAdmin.routes(self)

  require 'scripts/robots_generator'
  get '/robots.txt', to: RobotsGenerator

  get 'comments/recent'

  resources :identities, only: :destroy
  get 'welcome/index'
  devise_for :users,
             controllers: {omniauth_callbacks: 'sessions', registrations: 'registrations'},
             path_names: {:sign_in => 'login', :sign_out => 'logout'}

  resources :categories, only: :index

  resources :categories, path: '', only: [:show] do
    scope module: :training do
      resources :disks, only: [:index, :show] do
        member do
          constraints(question_number: /\d+/) do
            get :test, path: ':question_number'
            post :test_answer, path: ':question_number'
            get :view, path: ':question_number/view'
          end
          get :finish
          get :history
          get :attempt, path: 'attempt/:attempt_id', constraints: { attempt_id: /\d+/ }
        end
      end

      resources :questions, only: [:index, :show] do
        member do
          post :answer
          get :view
        end
      end
    end
  end

  get 'payments/new', as: 'new_payment'
  post 'payments/callback'

  root 'welcome#index'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :slug, :name

  # See http://norman.github.io/friendly_id/4.0/
  extend FriendlyId
  friendly_id :slug, use: [:finders]


  has_many :questions, dependent: :destroy
  has_many :disks, dependent: :destroy

  def next_disk(disk)
    disks.at(disks.index(disk) + 1)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  add_breadcrumb 'Главная', :root_path

  # GET /categories
  # GET /categories.json
  def index
    add_breadcrumb 'Тесты 1С'
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    add_breadcrumb 'Тесты 1С', categories_path
    add_breadcrumb @category.name
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.slim
- title 'Категории'

h1 Тесты 1С Профессионал - онлайн подготовка

- unless @categories.empty?
  .row
    - @categories.each do |category|
      .col-md-6
        .category-line.panel.panel-categories
          .panel-heading
            h2 #{category.name}
          .panel-body
            = category.description
          .footer
            = link_to 'По дискам', category_disks_path(category)
            = link_to 'По вопросам', category_questions_path(category)
      div class="#{cycle('', 'clearfix', name: 'category-clearfix')}"

  #categories-seo
    h2 1С тесты онлайн
    p В каждой категории собрано большое количество тестов по 1С для подготовки к тестированию 1С:Профессионал. Тесты 1С представляют собой группы по 14 закрытых вопросов, то есть таких, на которые нужно выбрать один ответ из нескольких предложенных вариантов. Тест 1С считается пройденным, если дано не менее 12 правильных ответов.
    p 1С разделяет тесты на несколько групп по областям знаний. На данный момент на сервисе онлайн подготовки к тестам 1С представлены наиболее популярные группы, получение сертфиката по которым дает много преимуществ для Вас. Успешная сдача тестов 1С по платформе, например, позволит Вам подтвердить свои знания основ платформы и откроет двери для сдачи экзамена 1С:Специалист. Тесты 1С по Бухгалтерии предприятия очень полезны для бухгалтера.

- else
  p Что-то ничего еще не загрузили...

app/views/categories/show.html.slim
- title @category.name

h1 = @category.name

- if admin?
  .admin-action = link_to 'Редактировать категорию', edit_admin_category_path(@category)

p = @category.description

p = @category.full_description

p Варианты подготовки к тестированию:

.list-group
  a.list-group-item href="#{category_disks_path(@category)}"
    h4.list-group-item-heading
      ' По дискам
    p.list-group-item-text
      | Классический вариант тестирования - вопросы сгруппированы по дискам ИТС, поставляемым фирмой 1С.
      | В каждом диске собрано 14 вопросов, история прохождения тестирования собирается по дискам.
  a.list-group-item href="#{category_questions_path(@category)}"
    h4.list-group-item-heading
      ' По вопросам
      span.label.label-info Новый
    p.list-group-item-text
      | Новый вариант тестирования - по всем вопросам выбранного раздела. Вы можете отбирать еще не изученные вопросы,
        вопросы, которые Вы начали изучать и полностью освоенные вопросы.