config/routes.rb
Gtests::Application.routes.draw do

  if(AppSettings['redirect_domains']) 
    domains = AppSettings['redirect_domains']
    domains = domains.join('|') if domains.is_a? Array
    constraints(host: /^(#{domains})\./i) do
      match '(*any)' => redirect { |params, request|
        URI.parse(request.url).tap { |uri| uri.host.sub!(/^(#{domains})\./i, '') }.to_s
      }, via: [:get, :post]
    end
  end

  get '/feedback', to: 'feedback#new'
  resources :feedback, only: [:new, :create]

  get 'page/agreement'
  get 'page/faq'

  get "payments/callback"
  get "payments/new"
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get "questions/show"
  get "questions/index"
  get "questions/test"
  mount Rich::Engine => '/rich', :as => 'rich'
  get "comments/recent"
  ActiveAdmin.routes(self)

  require 'scripts/robots_generator'
  get '/robots.txt', to: RobotsGenerator

  get 'comments/recent'

  resources :identities, only: :destroy
  get 'welcome/index'
  devise_for :users,
             controllers: {omniauth_callbacks: 'sessions', registrations: 'registrations'},
             path_names: {:sign_in => 'login', :sign_out => 'logout'}

  resources :categories, only: :index

  resources :categories, path: '', only: [:show] do
    scope module: :training do
      resources :disks, only: [:index, :show] do
        member do
          constraints(question_number: /\d+/) do
            get :test, path: ':question_number'
            post :test_answer, path: ':question_number'
            get :view, path: ':question_number/view'
          end
          get :finish
          get :history
          get :attempt, path: 'attempt/:attempt_id', constraints: { attempt_id: /\d+/ }
        end
      end

      resources :questions, only: [:index, :show] do
        member do
          post :answer
          get :view
        end
      end
    end
  end

  get 'payments/new', as: 'new_payment'
  post 'payments/callback'

  root 'welcome#index'

  

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :disk
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :user_answers, dependent: :destroy
  has_many :user_question_results, dependent: :destroy

  has_many :duplicates, class_name: 'Question', foreign_key: 'duplicate_of_id'
  belongs_to :duplicate_of, class_name: 'Question'

  default_scope { order('questions.disk_id, questions.order ASC, questions.id') }
  scope :no_duplicates, -> { where(duplicate_of: nil) }

  def to_s
    text.truncate(50)
  end

  def correct_answer
    answers.where(correct: true).first
  end

end

app/controllers/training/base_controller.rb
class Training::BaseController < ApplicationController
  before_action :set_category
  before_filter :add_breadcrumb_category

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def add_breadcrumb_category
    add_breadcrumb 'Тесты 1С', categories_path
    add_breadcrumb @category.name.truncate(60), category_path(@category)
  end

  def controller_index_path
  end
end

app/controllers/training/disks_controller.rb
class Training::DisksController < Training::BaseController
  #add_breadcrumb 'Главная', :root_path

  include QuestionsTraining

  before_filter :authenticate_user!, except: [:index]

  before_filter :set_disk, except: [:index]
  before_filter :add_breadcrumb_disk, except: [:index]
  before_filter :set_question, except: [:index, :show, :finish, :attempt, :history]
  before_filter :set_user_attempt, except: [:index, :view, :attempt, :history]
  before_filter :set_user_answer, only: [:test, :test_answer]

  def index
    @disks = @category.disks.with_questions.page(params[:page]).per(10)
    @scores = UserAttempt.best_scores(current_user, @disks.to_a) if current_user
  end

  def show
    question_number = @attempt.next_question_number
    if question_number
      redirect_to test_category_disk_path(@category, @disk, question_number: question_number)
    end
  end

  def test
  end

  def test_answer
    if @user_answer.update_attributes(user_answer_params)
      if @attempt.remains_questions_count > 0
        redirect_to path_for_question @attempt.next_question_number(@question_index + 1)
      else
        redirect_to finish_category_disk_path @category, @disk
      end
    else
      flash[:error] = @user_answer.errors.full_messages.to_sentence
      render 'training/disks/test'
    end
  end

  def finish
    if @attempt.new_record?
      flash[:notice] = 'Отсутствует незавершенная попытка'
      if UserAttempt.where(user: current_user, disk: @disk).count > 0
        redirect_to history_category_disk_path(@category, @disk)
      else
        redirect_to test_category_disk_path(@category, @disk, 1)
      end
    else
      @attempt.finish
      redirect_to attempt_category_disk_path(@category, @disk, @attempt, finish: true)
    end
  end

  def attempt
    add_breadcrumb 'Детально'
    @attempt = UserAttempt.includes(disk: [:questions => [:category]]).find(params[:attempt_id])
    @user = @attempt.user unless @attempt.user == current_user
  end

  def history
    add_breadcrumb 'Результаты'
    @attempts = @disk.user_attempts.where(user: current_user).order('completed_at desc')
  end

  def view
    answer = Answer.find_by(id: params[:answer])
    @question_view_info = QuestionViewInfo.new(@question, answer: answer)
  end

  protected

  # Needed for Merit, otherwise it gets Question
  def target_object
    @user_answer
  end

  private

  def set_disk
    @disk = Disk.find(params[:id])
  end

  def add_breadcrumb_disk
    add_breadcrumb 'По дискам', category_disks_path(@category)
    add_breadcrumb @disk.name_in_lists, category_disk_path(@category, @disk)
  end

  def set_question
    questions_count = @disk.questions.count
    @question_index = params[:question_number].to_i - 1
    if questions_count == 0
      redirect_to category_disk_path(@category, @disk)
    elsif @question_index < 0
      redirect_to path_for_question 1
    elsif @question_index >= questions_count
      redirect_to path_for_question questions_count
    end
    @question = @disk.questions.includes(:category, :answers).to_a[@question_index]
  end

  def set_user_attempt
    @attempt = UserAttempt.get_current_by_user_disk(current_user, @disk)
  end

  def set_user_answer
    attributes = {user: current_user, user_attempt: @attempt, question: @question}
    @user_answer = UserAnswer.where.not(user_attempt_id: nil).where(attributes).first
    @user_answer = UserAnswer.new(user: current_user, user_attempt: @attempt, question: @question) unless @user_answer
  end

  def path_for_question(question_number)
    url_for only_path: true,
            action: action_name,
            category_id: @category.slug,
            id: @disk.id,
            question_number: question_number
  end

  def controller_index_path
    category_disks_path(@category)
  end
end

app/controllers/training/questions_controller.rb
class Training::QuestionsController < Training::BaseController
  include QuestionsTraining

  before_filter :authenticate_user!
  before_filter :set_question, except: [:index]
  before_filter :set_user_answer, only: [:show, :answer]
  before_filter :prepare_question_view_info, only: [:show, :view, :answer]
  before_action :check_points_balance!, only: [:show, :view, :answer]

  def index
    @questions = filtered_questions.page(params[:page]).per(30)
  end

  def show
  end

  def view

  end

  def answer
    # old_questions_in_group = filtered_questions.ids
    next_question = filtered_questions.next_for(@question).limit(1).first
    updated = @user_answer.update_attributes(user_answer_params)
    @question_view_info.answer = @user_answer.answer
    if updated
      @question.percentage!
      # @question_view_info.find_next_question_within! old_questions_in_group
      @question_view_info.next_question = next_question

      ActiveSupport::Notifications.instrument('question.user_answered', user_answer_id: @user_answer.id)

      respond_to do |format|
        format.js { @question_view_info.options[:remote] = true }
        format.html do
          # redirect_to view_category_question_path(@category, @question, answer: @question_view_info.answer, params: @question_view_info.params)
          render 'training/questions/view'
        end
      end
    else
      respond_to do |format|
        format.js do
          render :json => { :error => @user_answer.errors.full_messages.to_sentence },
                 :status => :unprocessable_entity
        end
        format.html do
          flash[:errors] = @user_answer.errors.full_messages.to_sentence
          redirect_to category_question_path(@category, @question, params: @question_view_info.params)
        end
      end
    end
  end

  protected

  # Needed for Merit, otherwise it gets Question
  def target_object
    @user_answer
  end

  private

  def controller_index_path
    category_questions_path(@category)
  end

  def set_question
    @question = UserQuestion.user(current_user).where(category: @category, id: params[:id]).first!
  end

  def set_user_answer
    @user_answer = UserAnswer.find_or_initialize_by(user: current_user, question: @question, answer_id: nil)
  end

  def prepare_question_view_info
    @question_view_info = QuestionViewInfo.new(@question)
    @question_view_info.params[:filter] = params[:filter]
    respond_to do |format|
      format.js { @question_view_info.options[:remote] = true }
      format.html {}
    end
  end

  def filtered_questions
    questions = UserQuestion.user(current_user).includes(:category).where(category: @category)
    allowed_filters = %w(new learning learned starred)
    if allowed_filters.include? params[:filter]
      scope = "user_#{params[:filter]}"
      questions = questions.send(scope) if questions.respond_to? scope
    end
    questions
  end

  def check_points_balance!
    if current_user.points(category: Merit::Points::MONEY) <= 0
      # See http://stackoverflow.com/questions/5454806/rails-3-how-to-redirect-to-in-ajax-call
      flash[:notice] = 'Для выполнения действия необходим положительный баланс бонусов'
      flash.keep(:notice)
      respond_to do |format|
        format.html { redirect_to new_payment_path }
        format.js { render js: "window.location = '#{new_payment_path}'" }
      end
    end
  end
end

app/helpers/training/disks_helper.rb
module Training::DisksHelper
  def finish_attempt_path(attempt)
    finish_category_disk_path(attempt.disk.category, attempt.disk)
  end

  def attempt_path(attempt)
    attempt_category_disk_path(attempt.disk.category, attempt.disk, attempt)
  end

  def answer_disk_question_path(question)
    disk = question.disk
    test_category_disk_path(disk.category, disk, question_number(question))
  end

  def view_disk_question_path(question, attempt=nil)
    params = {}
    if attempt
      params[:attempt] = attempt.id
      answer = get_answer(question, attempt)
      params[:answer] = answer.id if answer
    end
    view_category_disk_path(question.category, question.disk, question_number(question), params)
  end

  def questions_array(disk)
    Kaminari.paginate_array(disk.questions).page(params[:question_number]).per(1)
  end

  def question_number(question)
    question.disk.questions.index(question) + 1
  end

  def total_questions(question)
    question.disk.questions.size
  end

  def answer_text_for_question(question, user_attempt)
    answer = get_answer(question, user_attempt)
    answer ? answer.text : 'Не отвечено'
  end

  def answer_class(question, user_attempt)
    answer = get_answer(question, user_attempt)
    return 'warning' unless answer
    answer.correct ? 'success' : 'danger'
  end

  def next_disk_link(disk, options = {})
    if disk.category.next_disk(disk)
      link_to 'Пройти следующий тест >', category_disk_path(disk.category, disk.category.next_disk(disk)), options
    end
  end

  def attempt_results(attempt)
    "#{attempt.correct_count || 0} из #{attempt.disk.questions.count}"
  end

  def requested_attempt_link
    if params[:attempt]
      link_to '<- Вернуться к результатам теста',
              attempt_category_disk_path(@question.category, @question.disk, params[:attempt])
    end
  end

  def disk_score_percentage(score, disk)
    percentage = [(100 * score / disk.questions.count / 10.0).ceil * 10, 99].min
    "#{percentage}%"
  end

  private

  def get_answer(question, user_attempt)
    user_answer = user_attempt.user_answers.where(question: question).first
    user_answer.answer if user_answer
  end
end

app/helpers/training/questions_helper.rb
module Training::QuestionsHelper

  def completion_class_for question
    "icons-completion-#{(question.percentage / 25 ).round * 25}#{'-new' unless question.started}"
  end

  def completion_icon_for question, icon_class=''
    "<span class=\"completion #{completion_class_for(question)} #{icon_class}\">&nbsp;</span>"
  end

  def question_path question, params={}
    category_question_path question.category, question, params
  end

  def answer_questions_question_path(question)
    category_question_path(question.category, question)
  end

  def view_questions_question_path(question)
    view_category_question_path(question.category, question)
  end

end

app/views/training/questions/_question.html.slim
.col-md-4
  .question-instance id="q-#{question.id}" data-question="#{question.id}"
    p = link_to question.text.truncate(100), category_question_path(question.category, question, \
      params: {filter: params[:filter]}), class: 'question-link', remote: true
    .question-info
      span.last-answer class="#{'invisible' unless question.last_answered}"
        ' Последний ответ:
        span.answered-date
          = question.last_answered.strftime('%d.%m.%Y') if question.last_answered
      == completion_icon_for question, 'pull-right'
      .clearfix
div class="#{cycle('', '', 'clearfix', name: 'questions-clearfix')}"

app/views/training/questions/_question_header.html.slim
h2
  | Вопрос №#{question.id}
  span.pull-right == completion_icon_for question

app/views/training/questions/_question_test.html.slim
h1
  | Вопрос №#{@question_view_info.question.id}
  span.pull-right == completion_icon_for @question_view_info.question

#question-error-explanation
  - if @user_answer.errors.any?
    ul
      - @user_answer.errors.full_message.each do |msg|
        li = msg

= render layout: 'training/shared/question_general', locals: {question: @question_view_info.question, no_disqus: true} do
  = semantic_form_for @user_answer, url: answer_category_question_path(@question_view_info.question.category, @question_view_info.question, \
      params: {filter: params[:filter]}), remote: @question_view_info.options[:remote], authenticity_token: true, method: :post do |f|
    = f.input :answer, as: :radio, collection: @question_view_info.question.answers, label_method: :text, member_label: :text, label: false
    .buttons
      = f.submit 'Ответить на вопрос', class: 'btn btn-primary', id: 'submit-button'
      /.icons-disqus-spinner.hidden#submit-spinner
      - if local_assigns[:show_balance] && show_balance
        = current_user_money(no_button: true, class: 'pull-right')

app/views/training/questions/_question_view.html.slim
h1
  | Вопрос №#{@question_view_info.question.id}
  span.pull-right == completion_icon_for @question_view_info.question
= render layout: 'training/shared/question_view', locals: {view_info: @question_view_info} do
  = link_to 'Следующий вопрос', question_path(@question_view_info.next_question, @question_view_info.params), \
    @question_view_info.options
  - if local_assigns[:show_balance] && show_balance
    = current_user_money(no_button: true, class: 'pull-right')

app/views/training/questions/_questions_page.html.slim
.row
  = render partial: 'training/questions/question', as: :question, collection: @questions

- if @questions.next_page
  .next-page.icons-disqus-spinner data-page="#{@questions.next_page}"

app/views/training/questions/answer.js.erb
(function() {
    $('#question-modal .modal-body').html("<%= j render('layouts/adsense_top') %><%=j(render(partial: 'training/questions/question_view', locals: {show_balance: true}))%>");
    $('#personal-area .points-info').html($('#question-modal .points-info').html());

    var $listItemCompletion = $("#q-<%= @question.id %> .completion");
    if($listItemCompletion[0]) {
        $listItemCompletion[0].className = $listItemCompletion[0].className.replace(/\s?icons-completion-\S+\s?/g, ' ');
        $listItemCompletion.addClass('<%= completion_class_for(@question) %>');
    }

    var $lastAnswer = $("#q-<%= @question.id %> .last-answer");
    $lastAnswer.find('.answered-date').html('<%= @question.last_answered.strftime('%d.%m.%Y') %>')
    $lastAnswer.removeClass('invisible');

    var hash = "#!/<%= @question.id %>/view";
    CountersInteraction.hit(hash);

})();

app/views/training/questions/index.html.slim
- title "#{@category.name} - вопросы"

.row.js-only#questions-list-header
  .col-md-6.col-md-push-6
    .btn-group.pull-right#questions-filter
      button.btn.btn-default.active#filter-all type="button" Все
      button.btn.btn-default#filter-new data-filter="new" type="button" Новые
      button.btn.btn-default#filter-learning data-filter="learning" type="button" На изучении
      button.btn.btn-default#filter-learned data-filter="learned" type="button" Изученные
      /button.btn.btn-default#filter-starred data-filter="starred" type="button" Помеченные

#question-modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-hidden="true" &times;
        | &nbsp;
        #question-header
      .modal-body
      /.modal-footer
        button.btn.btn-primary type="button" data-dismiss="modal" Exit

#questions-list
  = render 'questions_page'
  = paginate @questions

app/views/training/questions/index.js.slim
= render 'questions_page'

app/views/training/questions/show.html.slim
- title "#{@question_view_info.category.name} - вопрос №#{@question_view_info.question.id}"

/= render 'training/questions/question_header'

= render 'training/questions/question_test'

app/views/training/questions/show.js.erb
(function(){
    $('#question-modal .modal-body').html('<%= j render('layouts/adsense_top') %><%= j render('training/questions/question_test', show_balance: true) %>');
    var hash = "#!/<%= @question.id %>";
    window.location.hash = hash;
    CountersInteraction.hit(hash);
})();

app/views/training/questions/view.html.slim
- title "#{@question_view_info.category.name} - просмотр вопроса №#{@question_view_info.question.id}"

= render 'training/questions/question_view'